fix: new branch (#124)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,6 +49,74 @@ jobs:
           HCP_TF_ORG: ${{ secrets.TF_ORG }}
           HCP_TF_PROJECT: ${{ secrets.TF_PROJECT }}
           HCP_TF_TOKEN: ${{ secrets.TF_API_TOKEN }}
+        # It is CRUCIAL to set "execution-mode": "local"
+        # in the "data" object in the JSON request body
+        # in the cURL to create the TF workspace below.
+        #
+        # This ensures that terraform apply executes
+        # locally even though the state file is maintained
+        # in HCP Terraform.
+        #
+        # Without this, it would run on HCP's runner.
+        # There it would fail on terraform apply (but
+        # not on terraform init) with the message that modules
+        # referenced using `../../modules/<module folder>`
+        # could not be read:
+        #
+        # │ Error: Unreadable module directory
+        # │
+        # │ Unable to evaluate directory symlink: lstat ../../modules: no such file or
+        # │ directory
+        # ╵
+        # ╷
+        # │ Error: Unreadable module directory
+        # │
+        # │ The directory  could not be read for module "flowmazonfrontend" at
+        # │ main.tf:1.
+        # ╵
+        # Operation failed: failed running terraform init (exit 1)
+        # Error: Terraform exited with code 1.
+        #
+        #
+        # You can try to fix that by using git references
+        # for the two modules used by the preview-ephemeral
+        # root module that corresponds to the workspace:
+        #
+        # module "flowmazonfrontend" {
+        #   source = "git::https://github.com/EnableHub/flowmazondotnet.git//.iac/modules/flowmazonfrontend?ref=main"
+        #
+        # and
+        #
+        # module "db_branch" {
+        # source = "git::https://github.com/EnableHub/flowmazondotnet.git//.iac/modules/db_branch?ref=main"
+        #
+        # Then you would get an error if there are more than
+        # one modules being referenced via github references
+        # in the root module (a single module referenced like
+        # this is fine though, which is a bit bafffling):
+        #
+        # ╷
+        # │ Error: Failed to expand subdir globs
+        # │
+        # │ subdir ".iac/modules/flowmazonfrontend" not found
+        #
+        # Basically one of the modules cannot be deferennced.
+        #
+        # I did have the option of copying across the referenced
+        # modules into the dir of the root module, then
+        # modify the root module to change the references
+        # dynamiclly in GitHub Actions workflow. This
+        # would likely have worked and would have required
+        # only local relative path references because the
+        # moule folders would be within the root module's
+        # folder.
+        #
+        # However, I have instead chosen to execute the TF
+        # config locally while keeping the state file on
+        # HCP Terraform. This is acceptable as the
+        # GitHub Actions runner on which terraform apply
+        # runs is also a clean machine and the state is
+        # still persisted and managed by HCP Terraform.
         run: |
           WORKSPACE_NAME="preview-${PR_LABEL}"
           curl -sS \
@@ -122,19 +190,11 @@ jobs:
         # workspace's Variables in Terraform HCP.
         run: |
           terraform apply -auto-approve \
-          -var="managed_identity_name=${{ vars.MANAGED_IDENTITY_NAME }}" \
-          -var="vault_name=${{ vars.VAULT_NAME }}" \
-          -var="id_and_vault_resource_group_name=${{ vars.ID_AND_VAULT_RESOURCE_GROUP_NAME }}" \
-          -var="vault_secretname_for_connectionstring=${{ vars.VAULT_SECRETNAME_FOR_CONNECTIONSTRING }}" \
-          -var="secretname_for_psql_owner_connectionstring=${{ vars.SECRETNAME_FOR_PSQL_OWNER_CONNECTIONSTRING_PREFIX }}${{env.PR_LABEL}}" \
           -var="environmentname_for_secrets_and_variables=Preview" \
           -var="repository_for_secrets_and_variables=flowmazondotnet" \
           -var="neon_project_id=${{ secrets.TF_MANAGED_NEON_PROJECT_ID }}" \
           -var="neon_source_branch_id=${{ secrets.TF_MANAGED_NEON_SOURCE_BRANCH_ID }}" \
           -var="neon_new_branch_name=${{ vars.NEON_NEW_BRANCH_NAME_PREFIX }}${{env.PR_LABEL}}" \
-          -var="neon_database_name=${{ vars.NEON_DATABASE_NAME }}" \
-          -var="neon_app_role=${{ vars.NEON_APP_ROLE_PREFIX }}${{env.PR_LABEL}}" \
-          -var="neon_owner_role=${{ vars.NEON_OWNER_ROLE_PREFIX }}${{env.PR_LABEL}}" \
           -var="vercel_team_id=${{ secrets.VERCEL_TEAM_ID }}" \
           -var="vercel_project_name=${{ secrets.VERCEL_PROJECT_NAME_PREFIX }}${{env.PR_LABEL}}" \
           -var="vercel_app_domain_name=${{env.PR_LABEL}}.${{ vars.VERCEL_APP_APEX_DOMAIN_NAME }}" \
@@ -155,7 +215,7 @@ jobs:
 # for this particular Pull Request (except ACAP app for API,
 # which will be created at the same time as deployment due to
 # limitations of ACA app's Terraform resource; see
-# aca_app module's README)
+# aca_app module's README).
 #
 # As the workspace will run on HCP Terraform's runner, I
 # wouldn't bother with a job to run terraform apply on
